Update on-pr-approved.yml

diff --git a/.github/workflows/on-pr-approved.yml b/.github/workflows/on-pr-approved.yml
--- a/.github/workflows/on-pr-approved.yml
+++ b/.github/workflows/on-pr-approved.yml
@@ -62,17 +62,17 @@ jobs:
               exit 1
             fi
           done
+      - name: Find api.yaml y petstore.yaml
+          id: specs
+          run: |
+            mapfile -t SPEC_FILES < <(git ls-files 'apis/**/api.yaml' 'apis/**/petstore.yaml')
+            if [ ${#SPEC_FILES[@]} -eq 0 ]; then
+              echo "::error::No se encontró ningún archivo api.yaml ni petstore.yaml."
+              exit 1
+            fi
+            { echo 'specs<<EOF'; printf '%s\n' "${SPEC_FILES[@]}"; echo 'EOF'; } >> "$GITHUB_OUTPUT"
+            echo "::notice::Archivos encontrados: ${SPEC_FILES[*]}"
 
-      - name: Find api.yaml
-        id: specs
-        run: |
-          mapfile -t SPEC_FILES < <(git ls-files 'apis/**/api.yaml')
-          if [ ${#SPEC_FILES[@]} -eq 0 ]; then
-            echo "::error::No se encontró ningún archivo api.yaml."
-            exit 1
-          fi
-          { echo 'specs<<EOF'; printf '%s\n' "${SPEC_FILES[@]}"; echo 'EOF'; } >> "$GITHUB_OUTPUT"
-          echo "::notice::Archivos api.yaml encontrados: ${SPEC_FILES[*]}"
 
       - name: Run scoring & build summary
         run: |
